name: Muse Marketing Group
favicon: null
layout_spectrum: 0.43562542856670916
typography_spectrum: 0.27749249222688377
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5332307119388133
  lightness: 0.5768900737166405
  saturation: 0.6420682102907449
  rhythmicContrast: 0.5109174330718815
purpose: []
