name: Muse Marketing Group
favicon: null
layout_spectrum: 0.43562542856670916
typography_spectrum: 0.27749249222688377
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f06349'
    - '#ffffff'
    - '#f5a292'
    - '#f2806b'
    - '#f9cbc2'
  brandStrength: 0.5625
  lightness: 0.5768900737166405
  saturation: 0.6420682102907449
  rhythmicContrast: 0.5109174330718815
purpose: []
